quarkus.http.port=8627


quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://172.29.135.4:5432/gtecno
quarkus.datasource.username = admin
quarkus.datasource.password = 123456


quarkus.hibernate-orm.database.generation=drop-and-create